### ISSUE TITLE
Various GUI improvements

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#122]
- [ ] Settings pane: https://github.com/daisy/pipeline-gui/issues/69
- [ ] Default directories, and remembering last used directories: https://github.com/daisy/pipeline-gui/issues/30
- [ ] Validation and custom widgets: https://github.com/daisy/pipeline-gui/issues/58
- [ ] Move File > Exit to bottom of Menu: https://github.com/daisy/pipeline-gui/issues/76
