### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#35]
## May 2017 ![XL][]

- [x] Troubleshooting and bug reporting documentation
- [ ] [in progress] [Developer documentation (contributors guide)](https://github.com/daisy/pipeline-tasks/issues/93) ![M][]
- [ ] [in progress] [Generated documentation from code](https://github.com/daisy/pipeline-tasks/issues/94) ![L][]
- [ ] Website accessibility: see report Jostein

---
## October 2017

- [ ] [Software architecture documentation (high-level system design)](https://github.com/daisy/pipeline-tasks/issues/37)
- [ ] [in progress] [Finish user documentation](https://github.com/daisy/pipeline-tasks/issues/95)
- [ ] Tutorials
- [ ] [Framework documentation](https://github.com/daisy/pipeline-tasks/issues/38)?
- [ ] [Modules documentation](https://github.com/daisy/pipeline-tasks/issues/39)?

---

There are two places where we can put documentation: in special Maven artefacts attached to individual Pipeline bundles, or in a shared repository.

The special Maven artefacts are created when you build the bundles. They get the classifier "doc". The documentation is either generated by the build system, or comes from documentation files in the source code. We can use this branch: https://github.com/daisy/pipeline/tree/doc (PR https://github.com/daisy/pipeline/pull/485).

The shared repository is like a wiki. It just contains static files. We'll use this branch: https://github.com/daisy/pipeline/tree/wiki.

The contract for documentation (both bundles and wiki) is described [here](https://daisy.github.io/pipeline/wiki/documentation_contract.html).

The [website generator](https://github.com/daisy/pipeline/tree/website) aggregates all this content.

### [Introduction/home page](http://daisy.github.io/pipeline)

- [ ] Link to latest version (with OS detection)
- [ ] Feature highlights
- [x] Links to Download, Getting Help, Contribute

### [Download](http://daisy.github.io/pipeline/Download.html)

- [x] Description of the various packages
- [ ] Unofficial versions from the snaekobbi project (DEBs)
- [ ] Old versions from https://code.google.com/archive/p/daisy-pipeline/downloads
- [ ] Links to installation instructions (currently pointing to GUI)

### [Help](http://daisy.github.io/pipeline/Get-Help) (user oriented)

- [x] [Overview page](http://daisy.github.io/pipeline/Get-Help)
- [ ] [User Guide](https://github.com/daisy/pipeline-tasks/issues/95) (in progress)
- [ ] Troubleshooting and bug reporting
- [x] [Forums](http://www.daisy.org/forums/pipeline-2)

### [Contribute](http://daisy.github.io/pipeline/Contribute) (develop oriented)
- [ ] [Contributors guide](https://github.com/daisy/pipeline-tasks/issues/93)

### Other

- [ ] Background (history, goals, requirements, ...)
- [x] [Presentations](http://daisy.github.io/pipeline/wiki/Presentations) (not in main sitemap yet, not sure where it belongs, mix of user-oriented and developer-oriented and general stuff)
- [ ] Roadmap, requirements, project charters, work plans, ...
- [ ] About (DAISY Consortium, contributors, developers, ...)
- [x] Sitemap
- [ ] Contact

## Port documentation from old website

The new website should replace [http://www.daisy.org/pipeline2](http://www.daisy.org/pipeline2), so we should port any content that we want to keep.

- [ ] [intro](http://www.daisy.org/pipeline2) (background)
- [ ] [overview](http://www.daisy.org/pipeline2/overview) (more background, feature highlights etc.)
- [x] [development](http://www.daisy.org/pipeline2/development)
- [ ] [FAQ](http://www.daisy.org/pipeline2/faq)
- [ ] [blog](http://www.daisy.org/pipeline2/blog)?
- [ ] links to work plans?

See also the [home page on google code](https://code.google.com/archive/p/daisy-pipeline/).

## Port documentation from the google wiki

See the google [archive](https://code.google.com/archive/p/daisy-pipeline/wikis), and also @capitancambio's dropbox (you can find the link on Slack) (**BEWARE! THIS IS NOT THE LATEST VERSION!**)

The idea is to take the pages from the old wiki that are still relevant and useful, to bring them up to date and to include them in our new documentation.

One approach is to first port all the pages (even those that are not useful anymore) to Markdown but without changing the content, and to place them in an archived section of the new wiki. After everything has been archived we can start updating the content. This way we do not have to rely on Google to keep hosting the archive. An easier solution could be to simply push the old wiki repo to Github, but the wiki pages wouldn't be as readable as when we would convert them to Markdown.

### How to convert:
- Convert from Google wiki format to Markdown. It shouldn't be too difficult to support other formats, let me know if you have a request.
- I'm not sure what we should do with the metadata at the top. For now we could just comment them out, and if we think we need them for similar features as Google had, we can find a way.
  - `#summary` can be replaced with RDFa metadata, e.g.:
    
    ``` xml
    <meta property="dc:title" content="The title"/>
    ```
    
    This already works as expected. If you define no title, the first heading will be used. (And if there's no headings, the file name is used.)
  - `#labels`: Not supported for now.
  - `#sidebar`: For now the idea is to have a single navigation list for the whole site, so there's no need to specify anything. Parts of the navigation list could be collapsed if it gets too long.
- For now, we merge all sidebar pages (*Nav and *Toc) into a single YAML file maintained in the website generator: https://github.com/daisy/pipeline/tree/website/src/_data/_spines/wiki.yml. It has the following format:
  
  ``` yml
  - /wiki/Page_1.html
  - /wiki/Page_2.html
  - group: /wiki/Foo.html
    pages:
     - /wiki/Foo_1.html
     - /wiki/Foo_1.html
  ```
  
  The paths become links in the navigation list, the page's titles are used as link text.
- `<wiki.toc/>` may be replaced with `{{>toc}}`
- `{{>synopsis}}` may be used to automatically insert a description of the inputs and options of a script.
- Preferably use [fenced code blocks](http://kramdown.gettalong.org/syntax.html#language-of-code-blocks) with language (the second method is compatible with Github) because it makes it easier to do syntax highlighting.
- Script documentation should link to the XProc. This can be done by putting the following lines at the top:
  
  ``` xml
  <link rev="dp2:doc" href="../resources/xml/dtbook-to-zedai.xpl"/>
  <link rel="rdf:type" href="http://www.daisy.org/ns/pipeline/userdoc"/>
  ```
  
  This assumes the file is placed in the src/main/doc directory of the dtbook-to-zedai module. If placed in the wiki, it is not possible to do the relative path, so the href should be `http://www.daisy.org/pipeline/modules/dtbook-to-zedai/dtbook-to-zedai.xpl` (the name of the script in the catalog.xml).

#### USEFUL FOR PUBLIC

Script documentation. These could also be placed in the wiki, but to have it in the source code seems the better option.
- [ ] [DAISY202ToEPUB3Doc](https://code.google.com/archive/p/daisy-pipeline/wikis/DAISY202ToEPUB3Doc.wiki) (see [daisy202-to-epub3](https://github.com/daisy/pipeline-tasks/issues/44))
- [ ] [DTBookToEPUB3Doc](https://code.google.com/archive/p/daisy-pipeline/wikis/DTBookToEPUB3Doc.wiki) (see [dtbook-to-epub3](https://github.com/daisy/pipeline-tasks/issues/55))
- [ ] [DTBookToZedAIDoc](https://code.google.com/archive/p/daisy-pipeline/wikis/DTBookToZedAIDoc.wiki) (see [dtbook-to-zedai](https://github.com/daisy/pipeline-tasks/issues/36))
- [ ] [DTBookValidator](https://code.google.com/archive/p/daisy-pipeline/wikis/DTBookValidator.wiki) (see [dtbook-validator](https://github.com/daisy/pipeline-tasks/issues/50))
- [ ] [NimasFilesetValidator](https://code.google.com/archive/p/daisy-pipeline/wikis/NimasFilesetValidator.wiki) (see [nimas-fileset-validator](https://github.com/daisy/pipeline-tasks/issues/52))
- [ ] [ZedAIToEPUB3Doc](https://code.google.com/archive/p/daisy-pipeline/wikis/ZedAIToEPUB3Doc.wiki) (see [zedai-to-epub3](https://github.com/daisy/pipeline-tasks/issues/54))
- [ ] [ZedAIToHTML](https://code.google.com/archive/p/daisy-pipeline/wikis/ZedAIToHTML.wiki) (see [zedai-to-html](https://github.com/daisy/pipeline-tasks/issues/53))
- [ ] [ZedAIToPEFDoc](https://code.google.com/archive/p/daisy-pipeline/wikis/ZedAIToPEFDoc.wiki) (see [zedai-to-pef](https://github.com/daisy/pipeline-tasks/issues/45))

#### USEFUL FOR PUBLIC

- [x] [ValidationStatusXML](https://code.google.com/archive/p/daisy-pipeline/wikis/ValidationStatusXML.wiki)
  - I haven't moved it to the source code because it belongs to several modules.
- [x] [ValidationReportXML](https://code.google.com/archive/p/daisy-pipeline/wikis/ValidationReportXML.wiki)
  - I haven't moved it to the source code because it belongs to several modules.
- [x] [RuntimeConfigurationProperties](https://code.google.com/archive/p/daisy-pipeline/wikis/RuntimeConfigurationProperties.wiki)
- [ ] [Presentations](https://code.google.com/archive/p/daisy-pipeline/wikis/Presentations.wiki)
  - [x] Port wiki page
  - [ ] Recover HTML slides from RNIB workshop and eBook Accessibility Symposium presentation from old hg repository
  - [x] Embed YouTube videos
  - [x] Add Romain's XML Prague presentation
  - [ ] @rdeltour: Please add any other newer presentations that aren't in the list yet

#### USEFUL FOR PUBLIC

- project overview
- user guide attempts
- how to use authentication
- how to use the command line

Web UI
- [ ] [WebUIInstallation](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUIInstallation.wiki)
- [ ] [WebUIUsage](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUIUsage.wiki)
  - See also http://daisy.github.io/pipeline/wiki/webui/User-Guide
- [ ] [WebUIBranding](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUIBranding.wiki)

Other
- [ ] [UserConcepts](https://code.google.com/archive/p/daisy-pipeline/wikis/UserConcepts.wiki)
- [ ] [Licensing](https://code.google.com/archive/p/daisy-pipeline/wikis/Licensing.wiki)
- [ ] [AdminCommandLine](https://code.google.com/archive/p/daisy-pipeline/wikis/AdminCommandLine.wiki)
- [x] [WebServiceAuthentication](https://code.google.com/archive/p/daisy-pipeline/wikis/WebServiceAuthentication.wiki)
- [ ] [CommandLine](https://code.google.com/archive/p/daisy-pipeline/wikis/CommandLine.wiki)
- [ ] [Installation](https://code.google.com/archive/p/daisy-pipeline/wikis/Installation.wiki)
  - Should also include installation of Debian packages

#### USEFUL FOR DEVS

- script utility docs
- conventions
- notes about third party tools we use
- internal xml format notes

:
- [ ] [FrameworkDetailsDoc](https://code.google.com/archive/p/daisy-pipeline/wikis/FrameworkDetailsDoc.wiki) (see [Framework documentation](https://github.com/daisy/pipeline-tasks/issues/38))
- [ ] Framework_ApplicationLayers? (see [Framework documentation](https://github.com/daisy/pipeline-tasks/issues/38))
- [ ] [Framework_ErrorHandling](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_ErrorHandling.wiki) (see [Framework documentation](https://github.com/daisy/pipeline-tasks/issues/38))
- [ ] [Framework_Messaging](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_Messaging.wiki) (see [Framework documentation](https://github.com/daisy/pipeline-tasks/issues/38))
- [ ] Framework_ModularizationDesign? (see [Framework documentation](https://github.com/daisy/pipeline-tasks/issues/38))
- [ ] Framework_Modularization? (see [Modules documentation](https://github.com/daisy/pipeline-tasks/issues/39))
- [ ] Framework_Modularization_Requirements? (see [Modules documentation](https://github.com/daisy/pipeline-tasks/issues/39))
- [ ] [Framework_ModularizationUseCases](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_ModularizationUseCases.wiki) (see [Modules documentation](https://github.com/daisy/pipeline-tasks/issues/39))
- [ ] [Framework_Extensibility](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_Extensibility.wiki) (see [Modules documentation](https://github.com/daisy/pipeline-tasks/issues/39))

Other
- [ ] [FileUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/FileUtils.wiki)
- [x] [WebServiceAPI](https://code.google.com/archive/p/daisy-pipeline/wikis/WebServiceAPI.wiki)
- [ ] [HTMLUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/HTMLUtils.wiki)
- [ ] [WebUIInstallation](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUIInstallation.wiki)
- [ ] [EPUB3PubUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/EPUB3PubUtils.wiki)
- [ ] [XMLResources](https://code.google.com/archive/p/daisy-pipeline/wikis/XMLResources.wiki)
- [ ] [EPUB3ProductionOverview](https://code.google.com/archive/p/daisy-pipeline/wikis/EPUB3ProductionOverview.wiki)
- [ ] [TestingTipsAndWishList](https://code.google.com/archive/p/daisy-pipeline/wikis/TestingTipsAndWishList.wiki)
- [ ] [Versioning](https://code.google.com/archive/p/daisy-pipeline/wikis/Versioning.wiki)
- [ ] [HowToCreateANewModule](https://code.google.com/archive/p/daisy-pipeline/wikis/HowToCreateANewModule.wiki)
- [ ] [MediaOverlayUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/MediaOverlayUtils.wiki)
- [ ] [FileSetUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/FileSetUtils.wiki)
- [ ] [ScriptMetadataCleanup](https://code.google.com/archive/p/daisy-pipeline/wikis/ScriptMetadataCleanup.wiki)
- [ ] [FileSetDocument](https://code.google.com/archive/p/daisy-pipeline/wikis/FileSetDocument.wiki)
- [ ] [NamingConventions](https://code.google.com/archive/p/daisy-pipeline/wikis/NamingConventions.wiki)
- [ ] [HowToCreateANewDaisyBundle](https://code.google.com/archive/p/daisy-pipeline/wikis/HowToCreateANewDaisyBundle.wiki)
- [ ] [MediaTypeUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/MediaTypeUtils.wiki)
- [x] [WebServiceCreateJob](https://code.google.com/archive/p/daisy-pipeline/wikis/WebServiceCreateJob.wiki)
- [ ] [MetadataUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/MetadataUtils.wiki)
- [ ] [EPUB3OCFUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/EPUB3OCFUtils.wiki)
- [ ] [ZipUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/ZipUtils.wiki)
- [ ] [HowToCreateAConverter](https://code.google.com/archive/p/daisy-pipeline/wikis/HowToCreateAConverter.wiki)
- [ ] [Inception_ExternalCommandCall](https://code.google.com/archive/p/daisy-pipeline/wikis/Inception_ExternalCommandCall.wiki)
- [ ] [WebServicePush](https://code.google.com/archive/p/daisy-pipeline/wikis/WebServicePush.wiki)
- [ ] [WebServiceTesting](https://code.google.com/archive/p/daisy-pipeline/wikis/WebServiceTesting.wiki)
- [ ] [DTBookUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/DTBookUtils.wiki)
- [ ] [EPUB3NavUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/EPUB3NavUtils.wiki)
- [ ] [ZipManifestDocument](https://code.google.com/archive/p/daisy-pipeline/wikis/ZipManifestDocument.wiki)
- [ ] [TextUtils](https://code.google.com/archive/p/daisy-pipeline/wikis/TextUtils.wiki)
- [ ] [XProcFileOperations](https://code.google.com/archive/p/daisy-pipeline/wikis/XProcFileOperations.wiki)
- [ ] [SettingUpTheDevelopmentEnvironment](https://code.google.com/archive/p/daisy-pipeline/wikis/SettingUpTheDevelopmentEnvironment.wiki)
- [ ] [XProcErrorCodes](https://code.google.com/archive/p/daisy-pipeline/wikis/XProcErrorCodes.wiki)

#### HISTORICALLY NOTABLE?

- reasons for making decisions
- old release notes
- requirements lists
- workflows

:
- [ ] [Framework_ApplicationLayers](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_ApplicationLayers.wiki)
- [ ] [Framework_ModularizationDesign](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_ModularizationDesign.wiki)
- [ ] [Framework_Modularization](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_Modularization.wiki)
- [ ] [TTSProductionRequirements](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSProductionRequirements.wiki)
- [ ] [BrailleProductionTools](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleProductionTools.wiki)
- [ ] [BrailleMarkupElements](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleMarkupElements.wiki)
- [ ] [BrailleSpecificProductionWorkflows](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleSpecificProductionWorkflows.wiki)
- [ ] [WebUIReleaseNotes](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUIReleaseNotes.wiki)
- [ ] [ReleaseNotes](https://code.google.com/archive/p/daisy-pipeline/wikis/ReleaseNotes.wiki)
- [ ] [Requirements](https://code.google.com/archive/p/daisy-pipeline/wikis/Requirements.wiki)
- [ ] [UserGuideOverview](https://code.google.com/archive/p/daisy-pipeline/wikis/UserGuideOverview.wiki)
- [ ] [Inception_FilesetManipulation](https://code.google.com/archive/p/daisy-pipeline/wikis/Inception_FilesetManipulation.wiki)
- [ ] [ProjectCharterPhase2](https://code.google.com/archive/p/daisy-pipeline/wikis/ProjectCharterPhase2.wiki)
- [ ] [Framework_Testing](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_Testing.wiki)
- [ ] [ProcessingRequirements](https://code.google.com/archive/p/daisy-pipeline/wikis/ProcessingRequirements.wiki)
- [ ] [XProcAdoption](https://code.google.com/archive/p/daisy-pipeline/wikis/XProcAdoption.wiki)
- [ ] [WebUIDev](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUIDev.wiki)
- [ ] [Roadmap](https://code.google.com/archive/p/daisy-pipeline/wikis/Roadmap.wiki)
- [ ] [BraillePossibleSolution](https://code.google.com/archive/p/daisy-pipeline/wikis/BraillePossibleSolution.wiki)
- [ ] [BrailleWGExpectations](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleWGExpectations.wiki)
- [ ] [TTSProductionWorkflow](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSProductionWorkflow.wiki)
- [ ] [BraillePrototypeFeatureSet](https://code.google.com/archive/p/daisy-pipeline/wikis/BraillePrototypeFeatureSet.wiki)
- [ ] [BackgroundResources](https://code.google.com/archive/p/daisy-pipeline/wikis/BackgroundResources.wiki)
- [ ] [DeveloperDocumentation](https://code.google.com/archive/p/daisy-pipeline/wikis/DeveloperDocumentation.wiki)
- [ ] [Samples](https://code.google.com/archive/p/daisy-pipeline/wikis/Samples.wiki)
- [ ] [XProcEnginesComparison](https://code.google.com/archive/p/daisy-pipeline/wikis/XProcEnginesComparison.wiki)
- [ ] [DevelopmentTools](https://code.google.com/archive/p/daisy-pipeline/wikis/DevelopmentTools.wiki)
- [ ] [BrailleProductionToolPresentationTemplate](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleProductionToolPresentationTemplate.wiki)
- [ ] [BrailleProduction](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleProduction.wiki)
- [ ] [TTSProductionPreProcessing](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSProductionPreProcessing.wiki)
- [ ] [WebUIFunctionalRequirements](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUIFunctionalRequirements.wiki)
- [ ] [ModulesWishList](https://code.google.com/archive/p/daisy-pipeline/wikis/ModulesWishList.wiki)
- [ ] [Inception_Pipeline1Transformers](https://code.google.com/archive/p/daisy-pipeline/wikis/Inception_Pipeline1Transformers.wiki)
- [ ] [BrailleProductionWorkflow](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleProductionWorkflow.wiki)
- [ ] [BuildSystem](https://code.google.com/archive/p/daisy-pipeline/wikis/BuildSystem.wiki)
- [ ] [TTSProductionStructureAnalysis](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSProductionStructureAnalysis.wiki)
- [ ] [ModulesRefactoring](https://code.google.com/archive/p/daisy-pipeline/wikis/ModulesRefactoring.wiki)
- [ ] [ModuleSystemOverview](https://code.google.com/archive/p/daisy-pipeline/wikis/ModuleSystemOverview.wiki)
- [ ] [Tutorials](https://code.google.com/archive/p/daisy-pipeline/wikis/Tutorials.wiki)
- [ ] [DocumentationConventions](https://code.google.com/archive/p/daisy-pipeline/wikis/DocumentationConventions.wiki)
- [ ] [FrameworkCleanup](https://code.google.com/archive/p/daisy-pipeline/wikis/FrameworkCleanup.wiki)
- [ ] [BrailleProductionWishList](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleProductionWishList.wiki)
- [ ] [ZedAIToEPUB3Dev](https://code.google.com/archive/p/daisy-pipeline/wikis/ZedAIToEPUB3Dev.wiki)
- [ ] [BrailleFopRenderingReport](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleFopRenderingReport.wiki)
- [ ] [TTSWGOverview](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSWGOverview.wiki)
- [ ] [BraillePreProcessingSteps](https://code.google.com/archive/p/daisy-pipeline/wikis/BraillePreProcessingSteps.wiki)
- [ ] [EPUB3OCFUtilsDev](https://code.google.com/archive/p/daisy-pipeline/wikis/EPUB3OCFUtilsDev.wiki)
- [ ] [TTSProductionInteractivity](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSProductionInteractivity.wiki)
- [ ] [TTSSoftwareComparison](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSSoftwareComparison.wiki)
- [ ] [BrailleProductionDev](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleProductionDev.wiki)
- [ ] [ProjectCharterPhase1](https://code.google.com/archive/p/daisy-pipeline/wikis/ProjectCharterPhase1.wiki)
- [ ] [ComparisonOfMathMLContentElements](https://code.google.com/archive/p/daisy-pipeline/wikis/ComparisonOfMathMLContentElements.wiki)
- [ ] [ScriptPiping](https://code.google.com/archive/p/daisy-pipeline/wikis/ScriptPiping.wiki)
- [ ] [TTSMarkupSnippets](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSMarkupSnippets.wiki)
- [ ] [EPUB3NavUtilsDev](https://code.google.com/archive/p/daisy-pipeline/wikis/EPUB3NavUtilsDev.wiki)
- [ ] [ZedAIToHTMLDev](https://code.google.com/archive/p/daisy-pipeline/wikis/ZedAIToHTMLDev.wiki)

#### PROBABLY USELESS

nice ideas but unfinished:
- [Framework_Modularization_Requirements](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_Modularization_Requirements.wiki)
- [Framework_Configurability](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_Configurability.wiki)
- [HowToDocumentationTechnical](https://code.google.com/archive/p/daisy-pipeline/wikis/HowToDocumentationTechnical.wiki)
- [MediaTypeUtilsDev](https://code.google.com/archive/p/daisy-pipeline/wikis/MediaTypeUtilsDev.wiki)
- [Inception_Parameters](https://code.google.com/archive/p/daisy-pipeline/wikis/Inception_Parameters.wiki)
- [DAISY202ToEPUB3Dev](https://code.google.com/archive/p/daisy-pipeline/wikis/DAISY202ToEPUB3Dev.wiki)
- [UserGuideToc](https://code.google.com/archive/p/daisy-pipeline/wikis/UserGuideToc.wiki)
- [HTMLUtilsDev](https://code.google.com/archive/p/daisy-pipeline/wikis/HTMLUtilsDev.wiki)
- [InceptionNav](https://code.google.com/archive/p/daisy-pipeline/wikis/InceptionNav.wiki)
- [FileSetUtilsDev](https://code.google.com/archive/p/daisy-pipeline/wikis/FileSetUtilsDev.wiki)
- [BrailleAutomationLimitations](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleAutomationLimitations.wiki)
- [BrailleProductionComponents](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleProductionComponents.wiki)
- [DAISY3ToEPUB3Dev](https://code.google.com/archive/p/daisy-pipeline/wikis/DAISY3ToEPUB3Dev.wiki)
- [Scripts](https://code.google.com/archive/p/daisy-pipeline/wikis/Scripts.wiki)
- [DTBookToZedAIDev](https://code.google.com/archive/p/daisy-pipeline/wikis/DTBookToZedAIDev.wiki)
- [Framework_Documentation](https://code.google.com/archive/p/daisy-pipeline/wikis/Framework_Documentation.wiki)
- [MediaOverlayUtilsDev](https://code.google.com/archive/p/daisy-pipeline/wikis/MediaOverlayUtilsDev.wiki)
- [TTSAdapter](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSAdapter.wiki)
- [UserGuideIntro](https://code.google.com/archive/p/daisy-pipeline/wikis/UserGuideIntro.wiki)
- [WebUI](https://code.google.com/archive/p/daisy-pipeline/wikis/WebUI.wiki)
- [DocResourcesToc](https://code.google.com/archive/p/daisy-pipeline/wikis/DocResourcesToc.wiki)
- [UrlResolverBehavioral](https://code.google.com/archive/p/daisy-pipeline/wikis/UrlResolverBehavioral.wiki)
- [BrailleTranslationRequirements](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleTranslationRequirements.wiki)
- [DevNav](https://code.google.com/archive/p/daisy-pipeline/wikis/DevNav.wiki)
- [ModulesNav](https://code.google.com/archive/p/daisy-pipeline/wikis/ModulesNav.wiki)
- [Troubleshooting](https://code.google.com/archive/p/daisy-pipeline/wikis/Troubleshooting.wiki)

old minutes and such
- [BrailleWGOverview](https://code.google.com/archive/p/daisy-pipeline/wikis/BrailleWGOverview.wiki)
- [Workshop](https://code.google.com/archive/p/daisy-pipeline/wikis/Workshop.wiki)
- [Packaging_Specification](https://code.google.com/archive/p/daisy-pipeline/wikis/Packaging_Specification.wiki)
- [TTSProduction](https://code.google.com/archive/p/daisy-pipeline/wikis/TTSProduction.wiki)
- BrailleWG_*

- ConCall_*

- F2F*

- TTSWG_*

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"
