### ISSUE TITLE
Integration of TTS modules

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#4]
### integration pull requests
- [x] daisy/pipeline-assembly#38
- [x] daisy/pipeline-framework#45
- [x] daisy/pipeline-scripts-utils#43
- [x] daisy/pipeline-mod-tts#1
- [x] daisy/pipeline-mod-nlp#1
- [x] daisy/pipeline-scripts#34
- [x] daisy/pipeline-scripts-utils#39
### pipeline-script-utils
- [ ] move create-media-overlays + clean-media-overlays to mediaoverlay-utils
- [x] extract the "synthesize" p:choose in an separate (internal) XProc file
### daisy3-utils
- [x] new media-overlays, ncx, opf sub-directories
- [x] s/media-overlays/smil
- [x] note: duration calculation is not generic, document it
### filset-utils
- [x] check how to integrate Romain's `fileset-change-base` with Jostein's `fileset-move`
### dtbook-to-daisy3
- [x] the resource file is inlined in dtbook-to-epub3.convert, s/b extracted and ideally localized
- [x] get-css-uris.xsl can be moved to dtbook-utils
### osgi-libs
- [x] remove the com4j branch, the SAPI5 adapter now uses JNI
- [x] merge daisy-consortium/osgi-libs#22
### TTS Adapters
- [x] develop a TTS adapter for OS X (VoiceOver)
### Misc
- [ ] Mention ACapella in the release notes
