### ISSUE TITLE
Build system cleanup/revision

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#68]
The build system has become a real obstacle, especially for external contributors. There are various things we can do to make it more manageable.

## February 2017 ![L][]

- [x] [done] The super project: https://github.com/daisy/pipeline-tasks/issues/34
- [x] [ready] Put all runtime dependencies in POMs to make testing less painful: https://github.com/daisy/pipeline-tasks/issues/23, https://github.com/daisy/pipeline/pull/503 ![XS][]
- [x] [ready] Minimize number of places where dependency versions are declared: https://github.com/daisy/pipeline/pull/503 ![XS][]
- [x] Fix circular dependencies: https://github.com/daisy/pipeline-modules-common/pull/95, https://github.com/daisy/pipeline-mod-braille/pull/144, https://github.com/daisy/pipeline-scripts/pull/100 ![XS][]
- [x] Use same artifacts for compiling and running: https://github.com/daisy/pipeline/pull/503 ![XS][]
- [x] Replace commons-logging dependencies with jcl-over-slf4j: https://github.com/daisy/pipeline/pull/503 ![XS][]
- [x] Remove SLF4J implementations (notably logback-classic) from the (runtime) dependencies in order to make it easier to control logging in tests: https://github.com/daisy/pipeline/pull/503 ![XS][]

## May, June, July 2017
- [x] Generalize and refine super build script (more "Make-based" and less "Maven-based"): https://github.com/daisy/pipeline/commit/64181df105
- [x] Write tools to facilitate working with super project (`git subrepo-status`): https://github.com/daisy/pipeline/commit/6b18d6f390
- [x] Further automate release process: https://github.com/daisy/pipeline-tasks/issues/98

## May 2018
- [x] Stop using remote snapshots repositories: https://github.com/daisy/pipeline-tasks/issues/75 ![XS][]
- [x] Include only one version of guava (not a different one specially for epubcheck): https://github.com/daisy/pipeline-assembly/pull/132 ![M][]
- [x] Change the scope of the slf4j-api dependency to `compile` (currently `provided` in many places) ![XS][]
- [x] Make build work with -f &lt;path-to-pom&gt;: e.g. https://github.com/daisy/pipeline-assembly/issues/117 ![XS][]

## 2020
- [x] Instead of having dependency `<exclusions>` in the BOMs, exclude them from the declared dependencies in the artifact POMs (or make `provided`). ![XS][]

---
## Other ![M][]

- [x] [ready] Felix annotations: https://github.com/daisy/pipeline-tasks/issues/22 ![XS][]
- [x] epubcheck-adapter: why not use parent?
- [x] Move lifecycleMappingMetadata of scripts-parent, scripts-utils-parent, etc. to modules-parent
- [ ] Include only one version of Jing
- [ ] Fix warnings: https://github.com/daisy/pipeline-tasks/issues/42 ![S][]
- [ ] Make offline building possible
  - including integration tests with maven-invoker-plugin
  - https://github.com/daisy/pipeline/commit/5ef0f40ec8
  - use common-entities in tests that depend on certain resources
- [ ] Use the same dependency versions everywhere so that there can be no confusion about which version Maven includes when running tests. ![XS][] (see `make check-versions`)
- [ ] [doing] Full build (no internal versions): https://github.com/daisy/pipeline-tasks/issues/40 ![S][]
- [ ] [doing] Assembly clean up: https://github.com/daisy/pipeline-assembly/issues/75 ![S][]
- [ ] Generate Require-Bundle metadata: https://github.com/daisy/pipeline-tasks/issues/41 ![S][]

See branches:
- https://github.com/daisy/pipeline/compare/master...dependencies
- assembly-modularize (local)
- https://github.com/daisy/pipeline-assembly/compare/master...pom-clean
- https://github.com/daisy/pipeline/compare/master...versionless
- offline (local)

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"

**Comment by josteinaj** [comment]
Possibly related to #41: To enable xprocspec testing we currently have to add a Java file under `src/test/` and list the same dependencies as are listed in the POM. It's basically something you copy from another project and edit the list of dependencies. Is it possible to remove this requirement, and just enable xprocspec testing for all module projects (unless explicitly disabled in the project pom)?

**Comment by bertfrees** [comment]
In https://github.com/daisy/pipeline/compare/dependencies...script-tests I've done some work to make it easier to create tests. The boilerplate in both Java and POM is reduced to a minimum this way. I hope this is a good enough improvement so that we don't have to make it completely automatic which would be a step too far IMO. That's just too magic for me. It's also not easy to do, technically.

**Comment by bertfrees** [comment]
@rdeltour I suggest we start with these ones (that I put at the top). Does that sound OK to you?

**Comment by bertfrees** [comment]
See PR https://github.com/daisy/pipeline/pull/503.

**Comment by bertfrees** [comment]
> - Fix circular dependencies

The only circular dependency that I know of at the moment is between fileset-utils and mediatype-utils. (`px:unzip-fileset` uses `px:mediatype-detect` which uses `px:fileset-load`). We can solve this by replacing all `px:unzip-fileset` with the new `px:fileset-unzip` (https://github.com/daisy/pipeline-modules-common/commit/0dcbd4b9fc30d1535366aca213839d101d4503d7). `px:unzip-fileset` is used in epub3-to-daisy202 and epub3-to-pef.

**Comment by bertfrees** [comment]
@josteinaj Could you please review https://github.com/daisy/pipeline/compare/script-tests...remove-unzip-fileset? The tests succeed.

**Comment by josteinaj** [comment]
@bertfrees looks good

**Comment by bertfrees** [comment]
I've moved the items that haven't been done to "Later" and cleared the milestone for now.

**Comment by bertfrees** [comment]
> - Stop using remote snapshots repositories: https://github.com/daisy/pipeline-tasks/issues/75

@rdeltour I'd like to do this one. Any objections?

**Comment by bertfrees** [comment]
@josteinaj It seems that unzip-fileset was also used in epub3-dtbook-migrator. Have you noticed that?

**Comment by rdeltour** [comment]
> > Stop using remote snapshots repositories: #75
> 
> @rdeltour I'd like to do this one. Any objections?

No objections, go ahead.

**Comment by josteinaj** [comment]
@bertfrees yes, I'm trying to fix the nordic migrator (only some evasive weird issue with epubcheck remaining) ([nlbdev/pipeline@fix-nordic-migrator](https://github.com/nlbdev/pipeline/tree/fix-nordic-migrator)), and one issue was the renaming of unzip-fileset. It wasn't a big deal though, I just had to rename it: https://github.com/nlbdev/pipeline/commit/bce4267f98f31b0b0448699294aef2297dead1ac

**Comment by bertfrees** [comment]
OK. Just wanted to check because I also just come across this issue in the sbs branch.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-framework/pull/149
