### ISSUE TITLE
Refine the updater mechanism

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#70]
## February

- [x] [done] Make updater tool more suitable for command line use: https://github.com/daisy/pipeline-updater/pull/2
- [x] [done] Various fixes: https://github.com/daisy/pipeline-updater/compare/ba98bf6...86902c6 and https://github.com/daisy/pipeline-assembly/compare/0dd633d...2823103

## April
- [x] update URI not found on Windows: https://github.com/daisy/pipeline-tasks/issues/97 ![S][]

## August, Later
- [ ] Rename current to latest: https://github.com/daisy/pipeline-assembly/issues/123 ![XS][]

## Later
- [ ] Integrate updater in dp2: https://github.com/daisy/pipeline-cli-go/issues/14

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"

**Comment by bertfrees** [comment]
Postponing because other higher priority of other issues.
