### ISSUE TITLE
Source code cleanup/reorganisation

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#72]
## February 2017 ![M][]
- [x] Delete html-to-dtbook/poms: https://github.com/daisy/pipeline-scripts/commit/28caef ![XS][]
- [x] [ready] Remove brailleutils: https://github.com/daisy/osgi-libs/issues/30 ![XS][]
- [x] Copy tests from pipeline-it to webservice: https://github.com/daisy/pipeline-tasks/issues/67 ![M][]

## May 2017
- [x] Delete calabash-custom-steps: https://github.com/daisy/pipeline-assembly/commit/d706242d0e7c330c8f348a1f88927e814a3f6e8f ![XS][]

## April 2018
- [x] Move pipeline-braille-scripts to pipeline-scripts: https://github.com/daisy/pipeline-scripts/commit/abfc1d6f837836b46776d4f0b7c134a5f3da07be ![XS][]

## May 2018
- [x] Delete html-to-dtbook: https://github.com/daisy/pipeline-tasks/issues/61 ![XS][]

## February 2019
- [x] Move webservice-jaxb and clientlib-java-jaxb to framework
- [x] Move xproc-engine-daisy-pipeline to framework

## Next
I want to do the following two as soon as possible, but first all the PRs in the modules repositories should be merged.

- [x] Merge all modules (modules-common, scripts-utils, scripts, mod-tts, mod-audio, mod-nlp & mod-braille) into a single repository
- [x] [doing] Merge various pipeline-braille-utils in single modules ![M][]

## Later ![XL][]
- [x] Rename pipeline-cli to pipeline-cli-ruby
- [ ] Clean up and homogenize scripts code: https://github.com/daisy/pipeline-scripts/issues/141 ![L][]
- [ ] [doing] Include source code of (modified/OSGified) 3rd party libraries instead of fetching/patching: https://github.com/daisy/osgi-libs/pull/26 (done 2015/07), https://github.com/daisy/osgi-libs/issues/30 (done 2017/05), https://github.com/daisy/osgi-libs/pull/38 (done 2017/06), https://github.com/daisy/osgi-libs/pull/39 (done 2017/06), https://github.com/daisy/osgi-libs/issues/41 ![M][]
- [ ] Merge [fileset-to-zip-manifest.xsl](https://github.com/daisy/pipeline-modules-common/blob/master/fileset-utils/src/main/resources/xml/xslt/fileset-to-zip-manifest.xsl) and [fileset-to-zip-manifests.xsl](https://github.com/daisy/pipeline-modules-common/blob/master/fileset-utils/src/main/resources/xml/xslt/fileset-to-zip-manifests.xsl)?
  - for now I have just explained the difference in behavior
- [x] Is there a reason why there are three epub3-utils modules (nav, pub, ocf)? Could they be merged?
- [x] Could mediaoverlay-utils be merged with epub3-utils as well? Or would it make sense to rename it to smil-utils?
- [ ] Could epubcheck-adapter be merged with epub3-utils as well? Does epubcheck-adapter support other versions of EPUB?
- [ ] Delete tts-adapter-attnative? ![XS][]
- [ ] Homogenize directory structure of modules
- [ ] Merge manifest-from-fileset.xsl from odt-utils with fileset-to-odf-manifest.xsl from epub3-ocf-utils
  - if we rename odt-utils to odf-utils, it would acceptable for it to be a dependency of epub3-ocf-utils, because [ocf is based on odf](http://www.idpf.org/epub/31/spec/epub-ocf.html)
- [x] Distribute files in common-entities over other modules (html-utils, dtbook-utils, mediaoverlay-utils, etc.)
- [x] Wrap public XSLTs in XProc steps

## Wontfix
- ~~Move jaxp-standalone and zedval-osgi: https://github.com/daisy/pipeline-tasks/issues/66~~ ![XS][]
- ~~Remove px:zip-manifest-from-fileset?~~ (see below)
- ~~Delete persistence-mysql or remove from BoM (https://github.com/daisy/pipeline-framework/issues/130)~~ ![XS][]

---

Related:
- clean up snaekobbi repos: https://github.com/snaekobbi/issues/issues/31

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"

**Comment by bertfrees** [comment]
@rdeltour Let me know which items you think make sense to do now. None of them are really critical at the moment.

**Comment by bertfrees** [comment]
> - Remove px:zip-manifest-from-fileset?

@josteinaj You already deleted it in commit https://github.com/daisy/pipeline-modules-common/commit/c95c3505efa6ba3c8da7e1c5c98b5ca072c965bb but then @rdeltour added it back later. It seems that there is similar functionality in fileset-utils/src/main/resources/xml/xslt/fileset-to-zip-manifests.xsl. Is that the reason you removed it at first? There doesn't seem to be an XProc step for it though. px:zip-manifest-from-fileset is currently used in epub3-ocf-utils and odt-utils.

**Comment by josteinaj** [comment]
@bertfrees Its been a while since I commited that, but I think this is what happened:

I moved the XSLT from zip-utils to fileset-utils to avoid a circular dependency between the two modules.

I also removed `px:zip-manifest-from-fileset` since it only contained a single XSLT and thus wasn't really needed. Instead I exposed the XSLT through the catalog directly. If you think it makes sense, we could re-add it in fileset-utils (or maybe that's what @rdeltour already did).

**Comment by bertfrees** [comment]
I think it makes sense to have steps that wrap a single XSLT, if only because you have to write less to invoke it. Romain already re-added it in fileset-utils, yes, in order to fix epub3-ocf-utils and odt-utils). So I guess we don't have to do anything. I just thought there might be another reason why you deleted it. The only thing that bugs me a bit is that there are now two XSLT that seem to do very similar stuff, and I wonder whether they could be merged.

**Comment by josteinaj** [comment]
Oh I see, there's both fileset-to-zip-manifest.xsl, and fileset-to-zip-manifest**s**.xsl. By the looks of it, the last one seems to be more general, so maybe simply updating the references to this general XSLT and deleting the small XSLT would work.

**Comment by bertfrees** [comment]
Clearing the milestone for now.

**Comment by bertfrees** [comment]
In Leipzig we agreed to combine the following repositories into a single repository called "pipeline-modules"
- pipeline-modules-common
- pipeline-scripts-utils
- pipeline-mod-audio
- pipeline-mod-braille
- pipeline-mod-nlp
- pipeline-mod-tts
- pipeline-scripts

A next step could be to combine all "pipeline-x" repositories, but first we'll see how well this first step works out.

**EDIT**: The "modules-parent" project should also be moved from pipeline-build-utils to the new pipeline-modules and we could delete all the other parents if we want.

**EDIT 2**: We can make a common bom for all modules, which can contain 3rd party dependencies common to several module subrepos, like jStyleParser (now included in framework BOM).

**Comment by bertfrees** [comment]
Good news. It is now possible to transfer issues to other repositories. https://help.github.com/articles/transferring-an-issue-to-another-repository. We can use this to transfer the issues from all the modules repositories to the new "pipeline-modules" repository. We could also use this to transfer issues from the "pipeline" repository to the sub-repositories, or the other way around, move everything to the "pipeline" repository.

**Comment by bertfrees** [comment]
See PRs
- https://github.com/daisy/pipeline-modules-common/pull/114
- https://github.com/daisy/pipeline-scripts-utils/pull/98
- https://github.com/daisy/pipeline-scripts/pull/151

**Comment by bertfrees** [comment]
See new repo https://github.com/daisy/pipeline-modules

**Comment by bertfrees** [comment]
See PR https://github.com/daisy/pipeline-modules/pull/5
