### ISSUE TITLE
Pipeline as a library, dependency hell, OSGi

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#73]
## First ![L][]

- [x] [doing] Make less dependent on OSGi features, alternative mechanism for dependency injection (based on SPI): #31 ![L][]
  - [x] Start with minimal framework for using Pipeline modules outside Pipeline (see below)
  - [x] Modules
  - [x] Rest of framework
- [ ] Make components more generally usable (outside Pipeline): #28

---
## Later

- [ ] Clean up Java API, divide in layers
- [ ] Make modularity actually useful or otherwise combine modules: https://github.com/snaekobbi/pipeline-mod-braille/issues/49
- [ ] Loosen dependencies, make more dependencies optional: #29, #33
- [x] make liblouis-native and liblouis-tables directly usable by liblouis-java (not only through liblouis-core)
- ...

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"
