### ISSUE TITLE
Identify and fix bugs in DAISY 2.02 to EPUB 3

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#89]
- [x] [epub:textref in SMIL refers to .html files instead of .xhtml files](https://github.com/daisy/pipeline-scripts/issues/76) ![XS][]
- [x] [smil references inside links should also be removed](https://github.com/daisy/pipeline-scripts/issues/74) ![XS][]
- [x] [Remove superfluous xmlns:d from package document metadata](https://github.com/daisy/pipeline-scripts/issues/73) ![XS][]
- [x] [whenever a epub:textref attribute is added to a SMIL, a "attribute-value" attribute with the same value is added](https://github.com/daisy/pipeline-scripts/issues/75) ![XS][]

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"

**Comment by bertfrees** [comment]
See PRs:
- https://github.com/daisy/pipeline-scripts-utils/pull/87
- https://github.com/daisy/pipeline-scripts/pull/104
