### ISSUE TITLE
Identify and fix bugs in DTBook to EPUB 3

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#90]
- [x] [Spaces in paths of book files cause job failure](https://github.com/daisy/pipeline/issues/376) ![S][]
  - not an issue specific to dtbook-to-epub3
  - try to reproduce with v1.10
- [x] [Issues with spaces in dtbook-to-epub3 transformation ](https://github.com/daisy/pipeline-assembly/issues/94) ![S][]
- [x] [The "assert validity" option on dtbook-to-epub3 does not seem to work](https://github.com/daisy/pipeline-scripts/issues/67) ![XS][]
  - might be issue in dtbook-to-zedai and zedai-to-epub3 as well

Any other issues?

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"

**Comment by bertfrees** [comment]
I will add some unit tests but it's best to wait until https://github.com/daisy/pipeline-tasks/issues/92 is done before trying to fix the issues.

**Comment by bertfrees** [comment]
See PRs:
- https://github.com/daisy/pipeline-framework/pull/120
- https://github.com/daisy/pipeline-scripts/pull/104
