### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#95]
Result: http://daisy.github.io/pipeline/Get-Help/User-Guide

- [x] Overview page
- [ ] [in progress] Installation instructions ([result](http://daisy.github.io/pipeline/Get-Help/User-Guide/Installation/))
  - [x] instructions specific to web UI? (@josteinaj)
  - [ ] Mention Docker distribution
- [ ] [in progress] Desktop application ([result](http://daisy.github.io/pipeline/wiki/gui/DAISY-Pipeline-2-User-Guide))
  - [ ] Instructions for starting GUI on Linux/Debian
  - [ ] A bit more info under "Check updates"?
- [x] [in progress] Web application ([result](http://daisy.github.io/pipeline/wiki/webui/User-Guide))
  - [x] Bring up to date (currently for version 1.6) (@josteinaj)
- [ ] [in progress] Pipeline as a service ([result](http://daisy.github.io/pipeline/Get-Help/User-Guide/Pipeline-as-Service))
  - [ ] The Pipeline as a service and the CLI are also supported on Windows (cli added to %PATH%, webservice shortcut (**but why commented out?**)); this should be documented (@bertfrees)
  - [x] ~~Configuration files: "localfs" and "authentication" properties override whatever is specified in bin/pipeline2 if uncommented~~ (**EDIT**: not the case anymore) (@bertfrees)
  - [ ] Configuration files: mention "host.protection" property (@YLBrailleNet)
    - see also https://github.com/daisy/pipeline/issues/507
  - [ ] [Simplify configuration](https://github.com/daisy/pipeline-tasks/issues/115)
- [ ] Command line ([result](http://daisy.github.io/pipeline/Get-Help/User-Guide/Command-Line))
  - [ ] CLI on Windows (see "Pipeline as a service" above) (@bertfrees)
  - [x] Use updater via command line
    - see also https://github.com/daisy/pipeline-updater/issues/1, https://github.com/daisy
/pipeline-updater/pull/2
    - not yet for Windows
- [ ] [in progress] Script documentation ([result](http://daisy.github.io/pipeline/Get-Help/User-Guide/Scripts))
    - [ ] Fix all examples that use CLI (@bertfrees)
    - [ ] [daisy202-to-epub3](https://github.com/daisy/pipeline-tasks/issues/44)
    - [ ] [daisy202-validator](https://github.com/daisy/pipeline-tasks/issues/56)
    - [ ] [daisy3-to-daisy202](https://github.com/daisy/pipeline-tasks/issues/63)
    - [ ] [daisy3-to-epub3](https://github.com/daisy/pipeline-tasks/issues/57)
    - [ ] [dtbook-to-daisy3](https://github.com/daisy/pipeline-tasks/issues/58)
    - [ ] [dtbook-to-epub3](https://github.com/daisy/pipeline-tasks/issues/55)
    - [ ] [dtbook-to-html](https://github.com/daisy/pipeline-tasks/issues/59)
    - [ ] [dtbook-to-odt](https://github.com/daisy/pipeline-tasks/issues/49) (not yet included for now)
    - [ ] [dtbook-to-pef](https://github.com/daisy/pipeline-tasks/issues/46)
    - [ ] [dtbook-to-zedai](https://github.com/daisy/pipeline-tasks/issues/36)
    - [ ] [dtbook-validator](https://github.com/daisy/pipeline-tasks/issues/50)
    - [ ] [epub3-to-daisy202](https://github.com/daisy/pipeline-tasks/issues/60)
    - [ ] [epub3-to-pef](https://github.com/daisy/pipeline-tasks/issues/47)
    - [ ] [epub3-validator](https://github.com/daisy/pipeline-tasks/issues/51)
    - [ ] [html-to-dtbook](https://github.com/daisy/pipeline-tasks/issues/61) (should also not be included?)
    - [ ] [html-to-epub3](https://github.com/daisy/pipeline-tasks/issues/62)
    - [ ] [html-to-pef](https://github.com/daisy/pipeline-tasks/issues/48)
    - [ ] [nimas-fileset-validator](https://github.com/daisy/pipeline-tasks/issues/52)
    - [ ] [zedai-to-epub3](https://github.com/daisy/pipeline-tasks/issues/54)
    - [ ] [zedai-to-html](https://github.com/daisy/pipeline-tasks/issues/53)
    - [ ] [zedai-to-pef](https://github.com/daisy/pipeline-tasks/issues/45)
- [ ] [in progress] [Text-to-speech documentation](https://github.com/daisy/pipeline-tasks/issues/65) (@YLBrailleNet)

**Comment by josteinaj** [comment]
@bertfrees I've updated the Web UI wiki now, but I haven't tested building the website with the updated documentation. Could you review it and make sure that it's imported correctly into the website?

**Comment by bertfrees** [comment]
OK, I will.

**Comment by bertfrees** [comment]
Good job, thanks! Updated the website.
