### ISSUE TITLE
Fix various Benetech issues

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#96]
## April 2017
- [x] [the data directory of a volatile job is not always deleted if things went wrong](https://github.com/daisy/pipeline/issues/149) ![S][]

## September 2017
- [ ] [After conversion error, API call for job "result" returns 500 server error](https://github.com/daisy/pipeline/issues/369)
  - try to reproduce with v1.10
  - check if this is really a bug
- [ ] [Felix error after web service hung and restarted](https://github.com/daisy/pipeline/issues/195)
  - try to reproduce with v1.10

## April 2018
- [x] [split large text files by size](https://github.com/daisy/pipeline/issues/351) (--> moved to https://github.com/daisy/pipeline-tasks/issues/123)
  - related to performance on the reading system side
  - relevant for
    - daisy202-to-epub3?
    - daisy3-to-epub3?
    - dtbook-to-epub3?
    - html-to-epub3?
    - zedai-to-epub3? 

## Later
- [ ] [reconsider merging multiple dtbooks in dtbook-to-zedai](https://github.com/daisy/pipeline/issues/342)
- [ ] [Ability to stop/kill a job before it's finished running](https://github.com/daisy/pipeline/issues/168)
  - duplicate: [Allow jobs to be aborted](https://github.com/daisy/pipeline-framework/issues/76)

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"
